# Generated by Django 3.2.15 on 2022-09-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approves',
            new_name='approved',
        ),
    ]
